[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
ignore = ["D203", "D213"]
select = ["E", "F", "W", "I", "N", "D", "UP", "S", "B", "A", "C4", "T20", "Q", "RUF"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["S101", "PT011", "PT012"]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
python_version = "3.13"
show_error_codes = true
strict = true

[project]
author = "jesse naiman"
description = "A modular Python starter template with toggleable features (math, game dev, etc.)."
license = {text = "MIT"}
name = "zerostart"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"
