[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "wheel"]

[project]
authors = [
  {name = "Jesse Naim", email = "your.email@example.com"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jesseniman/zerostart"
Repository = "https://github.com/jessenaiman/zerostart"

[tool.ruff]
# Specify the directories or files to check
target = ["src", "tests"]
