[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "zerostart"
version = "0.1.0"
description = "Clean-slate Python project template"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{ include = "zerostart", from = "src" }]

[tool.poetry.scripts]
zerostart = "zerostart.cli:app"

[tool.poetry.dependencies]
python = "^3.13"
typer = "^0.12.3"

# Main dependencies will be added by install scripts
# Group-specific dependencies will go here

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
ruff = "^0.4.4"
